services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: dev
    container_name: falcon_frontend
    ports:
      - 80:80
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    depends_on:
      - backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: falcon_backend
    command: dev
    ports:
      - 8080:8080
    volumes:
      - ./server/src:/app/server/src
      - ./server/package.json:/app/server/package.json
      - ./server/tsconfig.json:/app/server/tsconfig.json
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.32
    container_name: falcon_db
    env_file:
      - .env
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    volumes:
      - ./database:/docker-entrypoint-initdb.d
